import { useTypedSelector } from "../../modules";

export const usePostState = () => {
  const {
    getPostsDone,
    getPostLoading,
    getPostDone,
    getPostError,
    getPostsError,
    getPostsLoading,
    createPostDone,
    createPostError,
    createPostLoading,
    thumnailUploadLoading,
    thumnailUploadDone,
    thumnailUploadError,
    thumnailURL,
    deletePostDone,
    deletePostError,
    deletePostLoading,
    getUserPostsDone,
    getUserPostsError,
    getUserPostsLoading,
    post,
    posts,
  } = useTypedSelector((state) => state.post);

  return {
    getPostsDone,
    getPostLoading,
    getPostDone,
    getPostError,
    getPostsError,
    getPostsLoading,
    createPostDone,
    createPostError,
    createPostLoading,
    thumnailUploadLoading,
    thumnailUploadDone,
    thumnailUploadError,
    thumnailURL,
    deletePostDone,
    deletePostError,
    deletePostLoading,
    getUserPostsDone,
    getUserPostsError,
    getUserPostsLoading,
    post,
    posts,
  };
};
